const siteData = [
  {
    id: 1,
    site: 'keepfrds',
    nickname: '朋友',
    base_url: 'pt.keepfrds.com',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 2,
    site: 'pthome',
    nickname: '铂金家',
    base_url: 'pthome.net',
    download_page: 'download.php?id={}&uid={uid}&hash={hash}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 1,
  },
  {
    id: 3,
    site: 'm-team',
    nickname: '馒头',
    base_url: 'api.m-team.cc',
    download_page: 'api/torrent/genDlToken',
    details_page: 'detail/{}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 4,
    site: 'hdsky',
    nickname: '天空',
    base_url: 'hdsky.me',
    download_page: 'download.php?id={}&passkey={passkey}&sign={sign}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 1,
  },
  {
    id: 6,
    site: 'pter',
    nickname: '猫站',
    base_url: 'pterclub.com',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 7,
    site: 'hdhome',
    nickname: '家园',
    base_url: 'hdhome.org',
    download_page: 'download.php?id={}&uid={uid}&hash={hash}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 1,
  },
  {
    id: 8,
    site: 'btschool',
    nickname: '学校',
    base_url: 'pt.btschool.club',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 9,
    site: 'ourbits',
    nickname: '我堡',
    base_url: 'ourbits.club',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 11,
    site: 'torrentccf',
    nickname: '他吹吹风',
    base_url: 'et8.org',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 14,
    site: 'ttg',
    nickname: '听听歌',
    base_url: 'totheglory.im',
    download_page: 'dl/{}/{passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 15,
    site: 'nanyangpt',
    nickname: '南洋',
    base_url: 'nanyangpt.com',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 17,
    site: 'hdcity',
    nickname: '城市',
    base_url: 'hdcity.city',
    download_page: 'download?id={}&cuhash={cuhash}',
    details_page: 't-{}',
    is_https: 2,
    cookie_required: 1,
  },
  {
    id: 18,
    site: 'nicept',
    nickname: '老师',
    base_url: 'www.nicept.net',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 19,
    site: '52pt',
    nickname: '52pt',
    base_url: '52pt.site',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 22,
    site: 'eastgame',
    nickname: '吐鲁番',
    base_url: 'pt.eastgame.org',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 23,
    site: 'ssd',
    nickname: '春天',
    base_url: 'springsunday.net',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 24,
    site: 'soulvoice',
    nickname: '聆音',
    base_url: 'pt.soulvoice.club',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 25,
    site: 'chdbits',
    nickname: '彩虹岛',
    base_url: 'ptchdbits.co',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 27,
    site: 'ptsbao',
    nickname: '烧包',
    base_url: 'ptsbao.club',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 29,
    site: 'hdarea',
    nickname: '好大',
    base_url: 'hdarea.club',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 30,
    site: 'hdtime',
    nickname: '时光',
    base_url: 'hdtime.org',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 31,
    site: '1ptba',
    nickname: '1ptba',
    base_url: '1ptba.com',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 32,
    site: 'hd4fans',
    nickname: '兽',
    base_url: 'pt.hd4fans.org',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 33,
    site: 'opencd',
    nickname: '皇后',
    base_url: 'open.cd',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 36,
    site: 'joyhd',
    nickname: '开心',
    base_url: 'www.joyhd.net',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 37,
    site: 'dmhy',
    nickname: '幼儿园',
    base_url: 'u2.dmhy.org',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 38,
    site: 'upxin',
    nickname: '好多油',
    base_url: 'pt.upxin.net',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 39,
    site: 'oshen',
    nickname: '奥申',
    base_url: 'www.oshen.win',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 1,
  },
  {
    id: 40,
    site: 'discfan',
    nickname: '蝶粉',
    base_url: 'discfan.net',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 1,
  },
  {
    id: 45,
    site: 'byr',
    nickname: '北邮人',
    base_url: 'byr.pt',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 51,
    site: 'dicmusic',
    nickname: '海豚',
    base_url: 'dicmusic.com',
    download_page:
      'torrents.php?action=download&id={}&authkey={authkey}&torrent_pass={torrent_pass}',
    details_page: 'torrents.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 52,
    site: 'skyeysnow',
    nickname: '天雪',
    base_url: 'skyey2.com',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'forum.php?mod=viewthread&tid={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 53,
    site: 'pt',
    nickname: '葡萄',
    base_url: 'pt.sjtu.edu.cn',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 54,
    site: 'hdroute',
    nickname: '路',
    base_url: 'www.hdroute.org',
    download_page: 'download.php?id={}&passkey={passkey}&from=rss',
    details_page: 'details.php?id={}',
    is_https: 0,
    cookie_required: 0,
  },
  {
    id: 56,
    site: 'haidan',
    nickname: '海胆',
    base_url: 'www.haidan.video',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?group_id={group_id}&torrent_id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 57,
    site: 'hdfans',
    nickname: '红豆饭',
    base_url: 'hdfans.org',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 1,
  },
  {
    id: 58,
    site: 'dragonhd',
    nickname: '龙之家',
    base_url: 'www.dragonhd.xyz',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 59,
    site: 'hitpt',
    nickname: '百川',
    base_url: 'www.hitpt.com',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 60,
    site: 'pttime',
    nickname: '时间',
    base_url: 'www.pttime.org',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 0,
  },
  {
    id: 63,
    site: 'hdatmos',
    nickname: '阿童木',
    base_url: 'hdatmos.club',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 64,
    site: 'greatposterwall',
    nickname: '海豹',
    base_url: 'greatposterwall.com',
    download_page:
      'torrents.php?action=download&id={}&authkey={authkey}&torrent_pass={torrent_pass}',
    details_page: 'torrents.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 65,
    site: 'hdpost',
    nickname: '普斯特',
    base_url: 'pt.hdpost.top',
    download_page: 'torrent/download/{}.{rsskey}',
    details_page: 'torrents/{}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 66,
    site: 'hares',
    nickname: '大白兔',
    base_url: 'club.hares.top',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 2,
    cookie_required: 1,
  },
  {
    id: 67,
    site: 'hudbt',
    nickname: '蝴蝶',
    base_url: 'hudbt.hust.edu.cn',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 68,
    site: 'audiences',
    nickname: '观众',
    base_url: 'audiences.me',
    download_page: 'download.php?id={}&downhash={downHash}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 69,
    site: 'piggo',
    nickname: '猪猪',
    base_url: 'piggo.me',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 70,
    site: 'wintersakura',
    nickname: '冬樱',
    base_url: 'wintersakura.net',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 72,
    site: 'hhanclub',
    nickname: '憨憨',
    base_url: 'hhanclub.top',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 75,
    site: 'pt0ffcc',
    nickname: '自由农场',
    base_url: 'pt.0ff.cc',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 76,
    site: 'redleaves',
    nickname: '红叶',
    base_url: 'leaves.red',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 79,
    site: 'ptchina',
    nickname: '铂金学院',
    base_url: 'ptchina.org',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 80,
    site: 'zhuque',
    nickname: '朱雀',
    base_url: 'zhuque.in',
    download_page: 'api/torrent/download/{}/{torrent_key}',
    details_page: 'torrent/info/{}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 81,
    site: 'zmpt',
    nickname: '织梦',
    base_url: 'zmpt.cc',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 82,
    site: 'rousi',
    nickname: '肉丝',
    base_url: 'rousi.zip',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 83,
    site: 'monikadesign',
    nickname: '莫妮卡',
    base_url: 'monikadesign.uk',
    download_page: 'torrents/download/{}.{rsskey}',
    details_page: 'torrents/{}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 84,
    site: 'cyanbug',
    nickname: '大青虫',
    base_url: 'cyanbug.net',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 86,
    site: 'ubits',
    nickname: '优堡',
    base_url: 'ubits.club',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 88,
    site: 'pandapt',
    nickname: '熊猫',
    base_url: 'pandapt.net',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 89,
    site: 'carpt',
    nickname: '车站',
    base_url: 'carpt.net',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 90,
    site: 'dajiao',
    nickname: '打胶',
    base_url: 'dajiao.cyou',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 91,
    site: 'shadowflow',
    nickname: '影',
    base_url: 'star-space.net',
    download_page: 'p_torrent/download.php?tid={}&passkey={passkey}',
    details_page: 'p_torrent/video_detail.php?tid={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 93,
    site: 'agsvpt',
    nickname: '末日',
    base_url: 'www.agsvpt.com',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 94,
    site: 'ptvicomo',
    nickname: '象岛',
    base_url: 'ptvicomo.net',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 95,
    site: 'qingwapt',
    nickname: '青蛙',
    base_url: 'www.qingwapt.com',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 96,
    site: 'xingtan',
    nickname: '杏坛',
    base_url: 'xingtan.one',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 97,
    site: 'hdkyl',
    nickname: '麒麟',
    base_url: 'www.hdkyl.in',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 98,
    site: 'ilolicon',
    nickname: '爱萝莉',
    base_url: 'share.ilolicon.com',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 99,
    site: 'gtkpw',
    nickname: 'GTK',
    base_url: 'pt.gtk.pw',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 100,
    site: 'wukongwendao',
    nickname: '悟空',
    base_url: 'wukongwendao.top',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 101,
    site: 'okpt',
    nickname: 'okpt',
    base_url: 'www.okpt.net',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 102,
    site: 'crabpt',
    nickname: '蟹黄堡',
    base_url: 'crabpt.vip',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 103,
    site: 'icc2022',
    nickname: '冰淇淋',
    base_url: 'www.icc2022.com',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 105,
    site: 'hddolby',
    nickname: '杜比',
    base_url: 'www.hddolby.com',
    download_page: 'download.php?id={}&uid={uid}&hash={hash}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 1,
  },
  {
    id: 106,
    site: 'kamept',
    nickname: '龟站',
    base_url: 'kamept.com',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 107,
    site: 'ptcafe',
    nickname: '咖啡',
    base_url: 'ptcafe.club',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 108,
    site: 'tosky',
    nickname: 'ToSky',
    base_url: 't.tosky.club',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 109,
    site: 'yemapt',
    nickname: 'YemaPT',
    base_url: 'www.yemapt.org',
    download_page: 'api/torrent/download?id={}',
    details_page: '#/torrent/detail/{}/',
    is_https: 1,
    cookie_required: 1,
  },
  {
    id: 110,
    site: 'ptlgs',
    nickname: '劳改所',
    base_url: 'ptlgs.org',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 111,
    site: 'lemonhd',
    nickname: '柠檬',
    base_url: 'lemonhd.club',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 112,
    site: 'raingfh',
    nickname: '雨',
    base_url: 'raingfh.top',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 113,
    site: 'njtupt',
    nickname: '浦园',
    base_url: 'njtupt.top',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 114,
    site: 'ptzone',
    nickname: 'PTzone',
    base_url: 'ptzone.xyz',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 115,
    site: 'hdclone',
    nickname: 'hdclone',
    base_url: 'pt.hdclone.org',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 116,
    site: 'kufei',
    nickname: '库非',
    base_url: 'kufei.org',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 117,
    site: 'tjupt',
    nickname: '北洋',
    base_url: 'tjupt.org',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
  {
    id: 118,
    site: 'hdvideo',
    nickname: '北洋',
    base_url: 'hdvideo.one',
    download_page: 'download.php?id={}&passkey={passkey}',
    details_page: 'details.php?id={}',
    is_https: 1,
    cookie_required: 0,
  },
] as const
export default siteData
